BlowOut/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace BlowOut.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public string Index()
        {
            
            return "Please call Support at <u><strong>801-555-1212</strong></u>. Thank you!";
        }
        public string Email(string name, string email)
        {
            var message = new MailMessage();
            message.To.Add(new MailAddress(email));  // replace with valid value 
            message.From = new MailAddress("testingbyumvc@gmail.com");  // replace with valid value
            message.Subject = "Confirmation of Contact";
            message.Body = name + ", thank you for your concern!";
            message.IsBodyHtml = true;

            using (var smtp = new SmtpClient())
            {
                var credential = new NetworkCredential
                {
                    UserName = "testingbyumvc@gmail.com",  // replace with valid value
                    Password = "Idahome1"  // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.Send(message);

                return "Thank you " + name + "! We will send you an email to " + email + "!";
            }
        }
    }
}

BlowOut/Controllers/RentalController.cs
using BlowOut.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using System.Net;
using System.Data.Entity;
using System.Data;

namespace BlowOut.Controllers
{
    public class RentalController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        // GET: Rental
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Clarinet(Instrument instrument)
        {
            instrument.Description = "Clarinet";
            instrument.Image = "Clarinet.png";
            
            return View();
        }
        public ActionResult Flute()
        {
            return View();
        }
        public ActionResult Trumpet()
        {
            return View();
        }
        public ActionResult Trombone()
        {
            return View();
        }
        public ActionResult Saxophone()
        {
            return View();
        }
        public ActionResult Tuba()
        {
            return View();
        }
        public ActionResult Rentals()
        {
            return View(db.Instruments.ToList());
        }

        // GET: Clients/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientID,FirstName,LastName,Address,City,State,Zip,Phone,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientID,FirstName,LastName,Address,City,State,Zip,Phone,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title BlowOut Musical Instrument Rentals</title>
    <link href="~/Content/myCSS.css" rel="stylesheet" />
    <link href="~/Content/w3styles.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top myFooterText">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BlowOut Instrument Rentals", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("RENTALS", "Index", "Rental")</li>
                    <li>@Html.ActionLink("ABOUT", "About", "Home")</li>
                    <li>@Html.ActionLink("CONTACT", "Index", "Contact")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content myFooterText">
        @RenderBody()
        <hr />
        
        <footer>
            <p>&copy; @DateTime.Now.Year BlowOut Instrument Rentals</p>
        </footer>
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>